config:
 info: common on baby ooo yyy ddd 222
spring:
  rabbitmq:
    host: 192.168.17.131
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
