spring:
  rabbitmq:
    host: 192.168.17.131
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders: # 在此配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.17.131
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型 本次为json 文本则“text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
